### ISSUE TITLE
Querying returns empty vector as data

### ISSUE THREAD

**Issue by solanav** [Shinmera/dns-client#4]
When using the current version published on github of dns-client, queryies are completed but return no data. As data I get an empty vector and as length I get zero.

![image](https://github.com/user-attachments/assets/6bccca8a-cf4f-4127-ba39-56886d03cb57)

**Comment by Shinmera** [comment]
it returns APL records, which the library doesn't know how to decode.

**Comment by solanav** [comment]
![image](https://github.com/user-attachments/assets/1300afd9-bc9b-41fc-92d1-7ce34e5b7a23)

Could it be :id being set to 42 (type APL in the types)?

**Comment by Shinmera** [comment]
The problem is in `decode-header` returning a bad end offset. I'm trying to figure out why.
